
DATA_LIST = [
    'ArmelR/stack-exchange-instruction',
    'HuggingFaceH4/CodeAlpaca_20K',
    'Open-Orca/OpenOrca',
    'Skywork/SkyPile-150B',
    'WizardLM/WizardLM_evol_instruct_V2_196k',
    'b-mc2/sql-create-context',
    'bigcode/starcoder',
    'burkelibbey/colors',
    'damo/MSAgent-Bench',
    'garage-bAInd/Open-Platypus',
    'mistralai/Mistral-7B-v0.1',
    'nampdn-ai/tiny-codes',
    'shibing624/medical',
    'silk-road/alpaca-data-gpt4-chinese',
    'tatsu-lab/alpaca',
    'timdettmers/openassistant-guanaco',
]

MODEL_LIST = [
    'internlm/internlm-7b', 
    'internlm/internlm-20b', 
    'internlm/internlm-chat-7b', 
    'internlm/internlm-chat-20b', 
    'meta-llama/Llama-2-7b-chat', 
    'meta-llama/llama2-70b', 
    'meta-llama/Llama-2-7b', 
    'huggyllama/llama-7b', 
    'baichuan-inc/Baichuan-7B-Chat', 
    'baichuan-inc/Baichuan-13B-Base', 
    'baichuan-inc/baichuan-7B', 
    'baichuan-inc/Baichuan2-13B-Chat', 
    'baichuan-inc/Baichuan2-7B-Chat', 
    'baichuan-inc/Baichuan2-13B-Chat', 
    'baichuan-inc/Baichuan2-13B-Base', 
    'THUDM/chatglm3-6b', 
    'THUDM/chatglm2-6b', 
    'THUDM/chatglm3-6b-base', 
    '01-ai/Yi-24B', 
    '01-ai/Yi-6B', 
    'Qwen/Qwen-7B-Chat', 
    'Qwen/Qwen-7B', 
]